# Generated by Django 5.2 on 2025-11-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='subtitle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='image')),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=50, verbose_name='button text')),
                ('button_url', models.CharField(blank=True, help_text='Relative URL such as /products/ or full URL', max_length=255, verbose_name='button URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
                'ordering': ('display_order', '-created_at'),
            },
        ),
    ]
