# Generated by Django 5.2 on 2025-11-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_demo_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='store_address_line1',
            field=models.CharField(blank=True, default='123 Main Street', max_length=255, verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_address_line2',
            field=models.CharField(blank=True, default='Your City, Your State', max_length=255, verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_country',
            field=models.CharField(blank=True, default='India', max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_email',
            field=models.EmailField(blank=True, default='info@priyankasuperbazaar.com', max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_hours',
            field=models.CharField(blank=True, default='Everyday, 8:00 AM – 10:00 PM', max_length=255, verbose_name='business hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_name',
            field=models.CharField(default='Priyanka Superbazaar', max_length=200, verbose_name='store name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_phone',
            field=models.CharField(blank=True, default='+91 1234567890', max_length=30, verbose_name='phone'),
        ),
    ]
