# Generated by Django 5.2 on 2025-12-07 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sitesettings_store_address_line1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('phone', models.CharField(help_text='Contact number of the delivery boy', max_length=15, verbose_name='phone number')),
                ('address', models.TextField(help_text='Current residential address', verbose_name='address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this delivery boy is active', verbose_name='is active')),
                ('current_location', models.CharField(blank=True, help_text='Last known location (latitude, longitude)', max_length=255, null=True, verbose_name='current location')),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number', max_length=20, verbose_name='vehicle number')),
                ('vehicle_type', models.CharField(blank=True, help_text='e.g., Bike, Scooter, Car', max_length=50, verbose_name='vehicle type')),
                ('id_proof', models.ImageField(help_text='Upload a scanned copy of ID proof (Aadhar, Driving License, etc.)', upload_to='delivery_boy/id_proofs/', verbose_name='ID proof')),
                ('aadhar_number', models.CharField(blank=True, help_text='12-digit Aadhar number', max_length=12, verbose_name='Aadhar number')),
                ('pan_number', models.CharField(blank=True, help_text='10-character PAN number', max_length=10, verbose_name='PAN number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'delivery boy',
                'verbose_name_plural': 'delivery boys',
                'ordering': ('-created_at',),
            },
        ),
    ]
