"""
URL configuration for config project.

Generated by 'django-admin startproject' using Django 4.2.7.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store.views import create_render_admin


admin.site.site_header = "Priyanka Superbazaar"
admin.site.site_title = "Priyanka Superbazaar"
admin.site.index_title = "Priyanka Superbazaar"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("store.urls")),
    path("create-render-admin/", create_render_admin),
]

# Serve media files in development

if settings.DEBUG and hasattr(settings, 'MEDIA_URL') and hasattr(settings, 'MEDIA_ROOT'):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)