"""
URL configuration for config project.

Generated by 'django-admin startproject' using Django 4.2.7.
"""
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store.views import create_render_admin
from store.views_seo import robots_txt
from store.sitemaps import StaticViewSitemap, CategorySitemap, ProductSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'categories': CategorySitemap,
    'products': ProductSitemap,
}


admin.site.site_header = "Priyanka Superbazaar"
admin.site.site_title = "Priyanka Superbazaar"
admin.site.index_title = "Priyanka Superbazaar"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", robots_txt, name="robots_txt"),
    path("", include("store.urls")),
    path("api/", include("store.api_urls")),
    path("create-render-admin/", create_render_admin),
]

# Serve media files in development

def _should_serve_media():
    """
    Only serve media via Django in DEBUG when MEDIA_URL/MEDIA_ROOT are explicitly
    configured. This prevents the default MEDIA_URL='/' from shadowing all routes.
    """
    media_url = getattr(settings, "MEDIA_URL", "") or ""
    media_root = getattr(settings, "MEDIA_ROOT", "") or ""

    # Django default MEDIA_URL is '/', which would match everything.
    if not media_root:
        return False
    if not media_url.startswith("/media/"):
        return False
    return True


if settings.DEBUG and _should_serve_media():
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)