"""
URL configuration for config project.

Generated by 'django-admin startproject' using Django 4.2.7.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "Priyanka Superbazaar"
admin.site.site_title = "Priyanka Superbazaar"
admin.site.index_title = "Priyanka Superbazaar"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("store.urls")),
]

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

